import { accentChair, albanySectional, albanyTable, armChair, diningTable, emperorBed, entertainmentCenter, highBackBench, leatherChair, leatherSofa, modernBookshelf, modernPoster, shelf, simpleChair, sofaSet, suedeArmchair, utopiaSofa, vaseTable, woodenBed, woodenDesk, woodenDesk1, woodenTable } from '../utils/index'

export const products_url = [
    {
      id: "recZkNf2kwmdBcqd0",
      name: "accent chair",
      price: 25999,
      image: accentChair,
      colors: ["#ff0000", "#00ff00", "#0000ff"],
      company: "marcos",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      category: "office",
      shipping: true,
    },
    {
      id: "recEHmzvupvT8ZONH",
      name: "albany sectional",
      price: 109999,
      image: albanySectional,
      colors: ["#000", "#ffb900"],
      company: "liddy",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      category: "living room",
    },
    {
      id: "rec5NBwZ5zCD9nfF0",
      name: "albany table",
      price: 309999,
      image: albanyTable,
      colors: ["#ffb900", "#0000ff"],
      company: "liddy",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      category: "kitchen",
    },
    {
      id: "recd1jIVIEChmiwhe",
      name: "armchair",
      price: 12599,
      image: armChair,
      colors: ["#000", "#00ff00", "#0000ff"],
      company: "marcos",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      category: "bedroom",
      shipping: true,
    },
    {
      id: "recotY5Nh00DQFdkm",
      name: "dining table",
      price: 42999,
      image: diningTable,
      colors: ["#00ff00", "#0000ff", "#ff0000"],
      company: "ikea",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      category: "dining",
      shipping: true,
    },
    {
      id: "rec1Ntk7siEEW9ha1",
      name: "emperor bed",
      price: 23999,
      image: emperorBed,
      colors: ["#0000ff", "#000"],
      company: "ikea",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      category: "bedroom",
      shipping: true,
    },
    {
      id: "recNZ0koOqEmilmoz",
      name: "entertainment center",
      price: 59999,
      image: entertainmentCenter,
      featured: true,
      colors: ["#000", "#ff0000"],
      company: "caressa",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      category: "living room",
      shipping: true,
    },
    {
      id: "recrfxv3EwpvJwvjq",
      name: "high-back bench",
      price: 39999,
      image: highBackBench,
      featured: true,
      colors: ["#000", "#00ff00"],
      company: "ikea",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      category: "office",
      shipping: true,
    },
    {
      id: "recoW8ecgjtKx2Sj2",
      name: "leather chair",
      price: 20099,
      image: leatherChair,
      colors: ["#ff0000", "#ffb900", "#00ff00"],
      company: "caressa",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      category: "bedroom",
    },
    {
      id: "recEOA6qtDag1hRbU",
      name: 'leather sofa',
      price: 99999,
      image: leatherSofa,
      colors: ["#00ff00", "#0000ff"],
      company: "caressa",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      category: "office",
    },
    {
      id: "recoAJYUCuEKxcPSr",
      name: "modern bookshelf",
      price: 31999,
      image: modernBookshelf,
      featured: true,
      colors: ["#ffb900", "#ff0000", "#00ff00"],
      company: "caressa",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      category: "kids",
    },
    {
      id: "recQ0fMd8T0Vk211E",
      name: "modern poster",
      price: 3099,
      image: modernPoster,
      colors: ["#000"],
      company: "liddy",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      category: "living room",
      shipping: true,
    },
    {
      id: "rec7CjDWKRgNQtrKe",
      name: "shelf",
      price: 30999,
      image: shelf,
      colors: ["#00ff00"],
      company: "ikea",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      category: "living room",
    },
    {
      id: "recF0KpwlkF7e8kXO",
      name: "simple chair",
      price: 109999,
      image: simpleChair,
      colors: ["#0000ff"],
      company: "liddy",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      category: "living room",
      shipping: true,
    },
    {
      id: "recs5BSVU3qQrOj4E",
      name: "sofa set",
      price: 129999,
      image: sofaSet,
      colors: ["#00ff00", "#ffb900"],
      company: "marcos",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      category: "living room",
      shipping: true,
    },
    {
      id: "recroK1VD8qVdMP5H",
      name: "suede armchair",
      price: 15999,
      image: suedeArmchair,
      colors: ["#ffb900"],
      company: "caressa",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      category: "office",
    },
    {
      id: "rec7JInsuCEHgmaGe",
      name: "utopia sofa",
      price: 79999,
      image: utopiaSofa,
      featured: true,
      colors: ["#ff0000", "#00ff00"],
      company: "liddy",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      category: "living room",
    },
    {
      id: "rec3jeKnhInKHJuz2",
      name: "vase table",
      price: 120999,
      image: vaseTable,
      featured: true,
      colors: ["#ff0000"],
      company: "marcos",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      category: "office",
    },
    {
      id: "recv2ohxljlK2FZO7",
      name: "wooden bed",
      price: 250099,
      image: woodenBed,
      colors: ["#000", "#ffb900"],
      company: "ikea",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      category: "bedroom",
    },
    {
      id: "recJIjREF3dlFi3sR",
      name: "wooden desk",
      price: 150999,
      image: woodenDesk,
      colors: ["#000"],
      company: "ikea",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      category: "office",
      shipping: true,
    },
    {
      id: "recm7wC8TBVdU9oEL",
      name: "wooden desk",
      price: 40099,
      image: woodenDesk1,
      colors: ["#0000ff", "#00ff00"],
      company: "ikea",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      category: "office",
    },
    {
      id: "rectfNsySwAJeWDN2",
      name: "wooden table",
      price: 234999,
      image: woodenTable,
      featured: true,
      colors: ["#ffb900", "#ff0000"],
      company: "caressa",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      category: "kitchen",
      shipping: true,
    },
  ];