import { accentChair, albanySectional, albanyTable, armChair, diningTable, emperorBed, entertainmentCenter, highBackBench, leatherChair, leatherSofa, modernBookshelf, modernPoster, shelf, simpleChair, sofaSet, suedeArmchair, utopiaSofa, vaseTable, woodenBed, woodenDesk, woodenDesk1, woodenTable, extraProduct1, extraProduct2, extraProduct3, extraProduct4 } from '../utils/index'

export const single_product_url = [
    {
      id: "recZkNf2kwmdBcqd0",
      stock: 3,
      price: 25999,
      shipping: true,
      colors: ["#ff0000", "#00ff00", "#0000ff"],
      category: "office",
      images: [
        {
          id: "attub6EG88kJKuYs8",
          width: 1000,
          height: 667,
          url: accentChair,
          filename: "product-4.jpeg",
          size: 49641,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: accentChair,
              width: 54,
              height: 36,
            },
            large: {
              url: accentChair,
              width: 768,
              height: 512,
            },
            full: {
              url: accentChair,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attaeT2Dex98o2jfW",
          width: 1000,
          height: 667,
          url: extraProduct1,
          filename: "extra-1.jpeg",
          size: 102108,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct1,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct1,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct1,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attWsZasaaRD1P7mm",
          width: 1000,
          height: 714,
          url: extraProduct2,
          filename: "extra-2.jpeg",
          size: 84418,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct2,
              width: 50,
              height: 36,
            },
            large: {
              url: extraProduct2,
              width: 717,
              height: 512,
            },
            full: {
              url: extraProduct2,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attTvaiDcADaAItLw",
          width: 1000,
          height: 650,
          url: extraProduct3,
          filename: "extra-3.jpeg",
          size: 107838,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct3,
              width: 55,
              height: 36,
            },
            large: {
              url: extraProduct3,
              width: 788,
              height: 512,
            },
            full: {
              url: extraProduct3,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attdxQmF0aCH5I32F",
          width: 1000,
          height: 667,
          url: extraProduct4,
          filename: "extra-4.jpeg",
          size: 99481,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct4,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct4,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct4,
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      reviews: 25,
      stars: 4.9,
      name: "accent chair",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      company: "marcos",
    },
    {
      id: "recEHmzvupvT8ZONH",
      stock: 0,
      price: 109999,
      colors: ["#000", "#ffb900"],
      category: "living room",
      images: [
        {
          id: "attub6EG88kJKuYs8",
          width: 1000,
          height: 667,
          url: albanySectional,
          filename: "product-4.jpeg",
          size: 49641,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: albanySectional,
              width: 54,
              height: 36,
            },
            large: {
              url: albanySectional,
              width: 768,
              height: 512,
            },
            full: {
              url: albanySectional,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attaeT2Dex98o2jfW",
          width: 1000,
          height: 667,
          url: extraProduct1,
          filename: "extra-1.jpeg",
          size: 102108,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct1,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct1,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct1,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attWsZasaaRD1P7mm",
          width: 1000,
          height: 714,
          url: extraProduct2,
          filename: "extra-2.jpeg",
          size: 84418,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct2,
              width: 50,
              height: 36,
            },
            large: {
              url: extraProduct2,
              width: 717,
              height: 512,
            },
            full: {
              url: extraProduct2,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attTvaiDcADaAItLw",
          width: 1000,
          height: 650,
          url: extraProduct3,
          filename: "extra-3.jpeg",
          size: 107838,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct3,
              width: 55,
              height: 36,
            },
            large: {
              url: extraProduct3,
              width: 788,
              height: 512,
            },
            full: {
              url: extraProduct3,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attdxQmF0aCH5I32F",
          width: 1000,
          height: 667,
          url: extraProduct4,
          filename: "extra-4.jpeg",
          size: 99481,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct4,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct4,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct4,
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      reviews: 123,
      stars: 3.3,
      name: "albany sectional",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      company: "liddy",
    },
    {
      id: "rec5NBwZ5zCD9nfF0",
      stock: 3,
      price: 309999,
      colors: ["#ffb900", "#0000ff"],
      category: "kitchen",
      images: [
        {
          id: "attub6EG88kJKuYs8",
          width: 1000,
          height: 667,
          url: albanyTable,
          filename: "product-4.jpeg",
          size: 49641,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: albanyTable,
              width: 54,
              height: 36,
            },
            large: {
              url: albanyTable,
              width: 768,
              height: 512,
            },
            full: {
              url: albanyTable,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attaeT2Dex98o2jfW",
          width: 1000,
          height: 667,
          url: extraProduct1,
          filename: "extra-1.jpeg",
          size: 102108,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct1,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct1,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct1,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attWsZasaaRD1P7mm",
          width: 1000,
          height: 714,
          url: extraProduct2,
          filename: "extra-2.jpeg",
          size: 84418,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct2,
              width: 50,
              height: 36,
            },
            large: {
              url: extraProduct2,
              width: 717,
              height: 512,
            },
            full: {
              url: extraProduct2,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attTvaiDcADaAItLw",
          width: 1000,
          height: 650,
          url: extraProduct3,
          filename: "extra-3.jpeg",
          size: 107838,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct3,
              width: 55,
              height: 36,
            },
            large: {
              url: extraProduct3,
              width: 788,
              height: 512,
            },
            full: {
              url: extraProduct3,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attdxQmF0aCH5I32F",
          width: 1000,
          height: 667,
          url: extraProduct4,
          filename: "extra-4.jpeg",
          size: 99481,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct4,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct4,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct4,
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      reviews: 34,
      stars: 3.6,
      name: "albany table",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      company: "liddy",
    },
    {
      id: "recd1jIVIEChmiwhe",
      stock: 3,
      price: 12599,
      shipping: true,
      colors: ["#000", "#00ff00", "#0000ff"],
      category: "bedroom",
      images: [
        {
          id: "attub6EG88kJKuYs8",
          width: 1000,
          height: 667,
          url: armChair,
          filename: "product-4.jpeg",
          size: 49641,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: armChair,
              width: 54,
              height: 36,
            },
            large: {
              url: armChair,
              width: 768,
              height: 512,
            },
            full: {
              url: armChair,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attaeT2Dex98o2jfW",
          width: 1000,
          height: 667,
          url: extraProduct1,
          filename: "extra-1.jpeg",
          size: 102108,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct1,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct1,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct1,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attWsZasaaRD1P7mm",
          width: 1000,
          height: 714,
          url: extraProduct2,
          filename: "extra-2.jpeg",
          size: 84418,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct2,
              width: 50,
              height: 36,
            },
            large: {
              url: extraProduct2,
              width: 717,
              height: 512,
            },
            full: {
              url: extraProduct2,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attTvaiDcADaAItLw",
          width: 1000,
          height: 650,
          url: extraProduct3,
          filename: "extra-3.jpeg",
          size: 107838,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct3,
              width: 55,
              height: 36,
            },
            large: {
              url: extraProduct3,
              width: 788,
              height: 512,
            },
            full: {
              url: extraProduct3,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attdxQmF0aCH5I32F",
          width: 1000,
          height: 667,
          url: extraProduct4,
          filename: "extra-4.jpeg",
          size: 99481,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct4,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct4,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct4,
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      reviews: 33,
      stars: 4.6,
      name: "armchair",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      company: "marcos",
    },
    {
      id: "recotY5Nh00DQFdkm",
      stock: 5,
      price: 42999,
      shipping: true,
      colors: ["#00ff00", "#0000ff", "#ff0000"],
      category: "dining",
      images: [
        {
          id: "attub6EG88kJKuYs8",
          width: 1000,
          height: 667,
          url: diningTable,
          filename: "product-4.jpeg",
          size: 49641,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: diningTable,
              width: 54,
              height: 36,
            },
            large: {
              url: diningTable,
              width: 768,
              height: 512,
            },
            full: {
              url: diningTable,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attaeT2Dex98o2jfW",
          width: 1000,
          height: 667,
          url: extraProduct1,
          filename: "extra-1.jpeg",
          size: 102108,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct1,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct1,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct1,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attWsZasaaRD1P7mm",
          width: 1000,
          height: 714,
          url: extraProduct2,
          filename: "extra-2.jpeg",
          size: 84418,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct2,
              width: 50,
              height: 36,
            },
            large: {
              url: extraProduct2,
              width: 717,
              height: 512,
            },
            full: {
              url: extraProduct2,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attTvaiDcADaAItLw",
          width: 1000,
          height: 650,
          url: extraProduct3,
          filename: "extra-3.jpeg",
          size: 107838,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct3,
              width: 55,
              height: 36,
            },
            large: {
              url: extraProduct3,
              width: 788,
              height: 512,
            },
            full: {
              url: extraProduct3,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attdxQmF0aCH5I32F",
          width: 1000,
          height: 667,
          url: extraProduct4,
          filename: "extra-4.jpeg",
          size: 99481,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct4,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct4,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct4,
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      reviews: 200,
      stars: 1.2,
      name: "dining table",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      company: "ikea",
    },
    {
      id: "rec1Ntk7siEEW9ha1",
      stock: 0,
      price: 23999,
      shipping: true,
      colors: ["#0000ff", "#000"],
      category: "bedroom",
      images: [
        {
          id: "attub6EG88kJKuYs8",
          width: 1000,
          height: 667,
          url: emperorBed,
          filename: "product-4.jpeg",
          size: 49641,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: emperorBed,
              width: 54,
              height: 36,
            },
            large: {
              url: emperorBed,
              width: 768,
              height: 512,
            },
            full: {
              url: emperorBed,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attaeT2Dex98o2jfW",
          width: 1000,
          height: 667,
          url: extraProduct1,
          filename: "extra-1.jpeg",
          size: 102108,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct1,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct1,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct1,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attWsZasaaRD1P7mm",
          width: 1000,
          height: 714,
          url: extraProduct2,
          filename: "extra-2.jpeg",
          size: 84418,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct2,
              width: 50,
              height: 36,
            },
            large: {
              url: extraProduct2,
              width: 717,
              height: 512,
            },
            full: {
              url: extraProduct2,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attTvaiDcADaAItLw",
          width: 1000,
          height: 650,
          url: extraProduct3,
          filename: "extra-3.jpeg",
          size: 107838,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct3,
              width: 55,
              height: 36,
            },
            large: {
              url: extraProduct3,
              width: 788,
              height: 512,
            },
            full: {
              url: extraProduct3,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attdxQmF0aCH5I32F",
          width: 1000,
          height: 667,
          url: extraProduct4,
          filename: "extra-4.jpeg",
          size: 99481,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct4,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct4,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct4,
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      reviews: 60,
      stars: 5,
      name: "emperor bed",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      company: "ikea",
    },
    {
      id: "recNZ0koOqEmilmoz",
      stock: 10,
      price: 59999,
      shipping: true,
      featured: true,
      colors: ["#000", "#ff0000"],
      category: "living room",
      images: [
        {
          id: "attub6EG88kJKuYs8",
          width: 1000,
          height: 667,
          url: entertainmentCenter,
          filename: "product-4.jpeg",
          size: 49641,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: entertainmentCenter,
              width: 54,
              height: 36,
            },
            large: {
              url: entertainmentCenter,
              width: 768,
              height: 512,
            },
            full: {
              url: entertainmentCenter,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attaeT2Dex98o2jfW",
          width: 1000,
          height: 667,
          url: extraProduct1,
          filename: "extra-1.jpeg",
          size: 102108,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct1,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct1,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct1,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attWsZasaaRD1P7mm",
          width: 1000,
          height: 714,
          url: extraProduct2,
          filename: "extra-2.jpeg",
          size: 84418,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct2,
              width: 50,
              height: 36,
            },
            large: {
              url: extraProduct2,
              width: 717,
              height: 512,
            },
            full: {
              url: extraProduct2,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attTvaiDcADaAItLw",
          width: 1000,
          height: 650,
          url: extraProduct3,
          filename: "extra-3.jpeg",
          size: 107838,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct3,
              width: 55,
              height: 36,
            },
            large: {
              url: extraProduct3,
              width: 788,
              height: 512,
            },
            full: {
              url: extraProduct3,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attdxQmF0aCH5I32F",
          width: 1000,
          height: 667,
          url: extraProduct4,
          filename: "extra-4.jpeg",
          size: 99481,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct4,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct4,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct4,
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      reviews: 100,
      stars: 3.6,
      name: "entertainment center",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      company: "caressa",
    },
    {
      id: "recrfxv3EwpvJwvjq",
      stock: 8,
      price: 39999,
      shipping: true,
      featured: true,
      colors: ["#000", "#00ff00"],
      category: "office",
      images: [
        {
          id: "attub6EG88kJKuYs8",
          width: 1000,
          height: 667,
          url: highBackBench,
          filename: "product-4.jpeg",
          size: 49641,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: highBackBench,
              width: 54,
              height: 36,
            },
            large: {
              url: highBackBench,
              width: 768,
              height: 512,
            },
            full: {
              url: highBackBench,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attaeT2Dex98o2jfW",
          width: 1000,
          height: 667,
          url: extraProduct1,
          filename: "extra-1.jpeg",
          size: 102108,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct1,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct1,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct1,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attWsZasaaRD1P7mm",
          width: 1000,
          height: 714,
          url: extraProduct2,
          filename: "extra-2.jpeg",
          size: 84418,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct2,
              width: 50,
              height: 36,
            },
            large: {
              url: extraProduct2,
              width: 717,
              height: 512,
            },
            full: {
              url: extraProduct2,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attTvaiDcADaAItLw",
          width: 1000,
          height: 650,
          url: extraProduct3,
          filename: "extra-3.jpeg",
          size: 107838,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct3,
              width: 55,
              height: 36,
            },
            large: {
              url: extraProduct3,
              width: 788,
              height: 512,
            },
            full: {
              url: extraProduct3,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attdxQmF0aCH5I32F",
          width: 1000,
          height: 667,
          url: extraProduct4,
          filename: "extra-4.jpeg",
          size: 99481,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct4,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct4,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct4,
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      reviews: 19,
      stars: 4.4,
      name: "high-back bench",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      company: "ikea",
    },
    {
      id: "recoW8ecgjtKx2Sj2",
      stock: 300,
      price: 20099,
      colors: ["#ff0000", "#ffb900", "#00ff00"],
      category: "bedroom",
      images: [
        {
          id: "attub6EG88kJKuYs8",
          width: 1000,
          height: 667,
          url: leatherChair,
          filename: "product-4.jpeg",
          size: 49641,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: leatherChair,
              width: 54,
              height: 36,
            },
            large: {
              url: leatherChair,
              width: 768,
              height: 512,
            },
            full: {
              url: leatherChair,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attaeT2Dex98o2jfW",
          width: 1000,
          height: 667,
          url: extraProduct1,
          filename: "extra-1.jpeg",
          size: 102108,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct1,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct1,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct1,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attWsZasaaRD1P7mm",
          width: 1000,
          height: 714,
          url: extraProduct2,
          filename: "extra-2.jpeg",
          size: 84418,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct2,
              width: 50,
              height: 36,
            },
            large: {
              url: extraProduct2,
              width: 717,
              height: 512,
            },
            full: {
              url: extraProduct2,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attTvaiDcADaAItLw",
          width: 1000,
          height: 650,
          url: extraProduct3,
          filename: "extra-3.jpeg",
          size: 107838,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct3,
              width: 55,
              height: 36,
            },
            large: {
              url: extraProduct3,
              width: 788,
              height: 512,
            },
            full: {
              url: extraProduct3,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attdxQmF0aCH5I32F",
          width: 1000,
          height: 667,
          url: extraProduct4,
          filename: "extra-4.jpeg",
          size: 99481,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct4,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct4,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct4,
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      reviews: 17,
      stars: 4.8,
      name: "leather chair",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      company: "caressa",
    },
    {
      id: "recEOA6qtDag1hRbU",
      stock: 4,
      price: 99999,
      colors: ["#00ff00", "#0000ff"],
      category: "office",
      images: [
        {
          id: "attub6EG88kJKuYs8",
          width: 1000,
          height: 667,
          url: leatherSofa,
          filename: "product-4.jpeg",
          size: 49641,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: leatherSofa,
              width: 54,
              height: 36,
            },
            large: {
              url: leatherSofa,
              width: 768,
              height: 512,
            },
            full: {
              url: leatherSofa,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attaeT2Dex98o2jfW",
          width: 1000,
          height: 667,
          url: extraProduct1,
          filename: "extra-1.jpeg",
          size: 102108,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct1,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct1,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct1,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attWsZasaaRD1P7mm",
          width: 1000,
          height: 714,
          url: extraProduct2,
          filename: "extra-2.jpeg",
          size: 84418,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct2,
              width: 50,
              height: 36,
            },
            large: {
              url: extraProduct2,
              width: 717,
              height: 512,
            },
            full: {
              url: extraProduct2,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attTvaiDcADaAItLw",
          width: 1000,
          height: 650,
          url: extraProduct3,
          filename: "extra-3.jpeg",
          size: 107838,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct3,
              width: 55,
              height: 36,
            },
            large: {
              url: extraProduct3,
              width: 788,
              height: 512,
            },
            full: {
              url: extraProduct3,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attdxQmF0aCH5I32F",
          width: 1000,
          height: 667,
          url: extraProduct4,
          filename: "extra-4.jpeg",
          size: 99481,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct4,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct4,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct4,
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      reviews: 44,
      stars: 3.3,
      name: "leather sofa",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      company: "caressa",
    },
    {
      id: "recoAJYUCuEKxcPSr",
      stock: 9,
      price: 31999,
      featured: true,
      colors: ["#ffb900", "#ff0000", "#00ff00"],
      category: "kids",
      images: [
        {
          id: "attub6EG88kJKuYs8",
          width: 1000,
          height: 667,
          url: modernBookshelf,
          filename: "product-4.jpeg",
          size: 49641,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: modernBookshelf,
              width: 54,
              height: 36,
            },
            large: {
              url: modernBookshelf,
              width: 768,
              height: 512,
            },
            full: {
              url: modernBookshelf,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attaeT2Dex98o2jfW",
          width: 1000,
          height: 667,
          url: extraProduct1,
          filename: "extra-1.jpeg",
          size: 102108,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct1,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct1,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct1,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attWsZasaaRD1P7mm",
          width: 1000,
          height: 714,
          url: extraProduct2,
          filename: "extra-2.jpeg",
          size: 84418,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct2,
              width: 50,
              height: 36,
            },
            large: {
              url: extraProduct2,
              width: 717,
              height: 512,
            },
            full: {
              url: extraProduct2,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attTvaiDcADaAItLw",
          width: 1000,
          height: 650,
          url: extraProduct3,
          filename: "extra-3.jpeg",
          size: 107838,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct3,
              width: 55,
              height: 36,
            },
            large: {
              url: extraProduct3,
              width: 788,
              height: 512,
            },
            full: {
              url: extraProduct3,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attdxQmF0aCH5I32F",
          width: 1000,
          height: 667,
          url: extraProduct4,
          filename: "extra-4.jpeg",
          size: 99481,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct4,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct4,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct4,
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      reviews: 27,
      stars: 4.2,
      name: "modern bookshelf",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      company: "caressa",
    },
    {
      id: "recQ0fMd8T0Vk211E",
      stock: 10,
      price: 3099,
      shipping: true,
      colors: ["#000"],
      category: "living room",
      images: [
        {
          id: "attub6EG88kJKuYs8",
          width: 1000,
          height: 667,
          url: modernPoster,
          filename: "product-4.jpeg",
          size: 49641,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: modernPoster,
              width: 54,
              height: 36,
            },
            large: {
              url: modernPoster,
              width: 768,
              height: 512,
            },
            full: {
              url: modernPoster,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attaeT2Dex98o2jfW",
          width: 1000,
          height: 667,
          url: extraProduct1,
          filename: "extra-1.jpeg",
          size: 102108,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct1,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct1,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct1,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attWsZasaaRD1P7mm",
          width: 1000,
          height: 714,
          url: extraProduct2,
          filename: "extra-2.jpeg",
          size: 84418,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct2,
              width: 50,
              height: 36,
            },
            large: {
              url: extraProduct2,
              width: 717,
              height: 512,
            },
            full: {
              url: extraProduct2,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attTvaiDcADaAItLw",
          width: 1000,
          height: 650,
          url: extraProduct3,
          filename: "extra-3.jpeg",
          size: 107838,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct3,
              width: 55,
              height: 36,
            },
            large: {
              url: extraProduct3,
              width: 788,
              height: 512,
            },
            full: {
              url: extraProduct3,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attdxQmF0aCH5I32F",
          width: 1000,
          height: 667,
          url: extraProduct4,
          filename: "extra-4.jpeg",
          size: 99481,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct4,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct4,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct4,
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      reviews: 100,
      stars: 2.2,
      name: "modern poster",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      company: "liddy",
    },
    {
      id: "rec7CjDWKRgNQtrKe",
      stock: 4,
      price: 30999,
      colors: ["#00ff00"],
      category: "living room",
      images: [
        {
          id: "attub6EG88kJKuYs8",
          width: 1000,
          height: 667,
          url: shelf,
          filename: "product-4.jpeg",
          size: 49641,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: shelf,
              width: 54,
              height: 36,
            },
            large: {
              url: shelf,
              width: 768,
              height: 512,
            },
            full: {
              url: shelf,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attaeT2Dex98o2jfW",
          width: 1000,
          height: 667,
          url: extraProduct1,
          filename: "extra-1.jpeg",
          size: 102108,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct1,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct1,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct1,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attWsZasaaRD1P7mm",
          width: 1000,
          height: 714,
          url: extraProduct2,
          filename: "extra-2.jpeg",
          size: 84418,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct2,
              width: 50,
              height: 36,
            },
            large: {
              url: extraProduct2,
              width: 717,
              height: 512,
            },
            full: {
              url: extraProduct2,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attTvaiDcADaAItLw",
          width: 1000,
          height: 650,
          url: extraProduct3,
          filename: "extra-3.jpeg",
          size: 107838,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct3,
              width: 55,
              height: 36,
            },
            large: {
              url: extraProduct3,
              width: 788,
              height: 512,
            },
            full: {
              url: extraProduct3,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attdxQmF0aCH5I32F",
          width: 1000,
          height: 667,
          url: extraProduct4,
          filename: "extra-4.jpeg",
          size: 99481,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct4,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct4,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct4,
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      reviews: 38,
      stars: 4.2,
      name: "shelf",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      company: "ikea",
    },
    {
      id: "recF0KpwlkF7e8kXO",
      stock: 7,
      price: 109999,
      shipping: true,
      colors: ["#0000ff"],
      category: "living room",
      images: [
        {
          id: "attub6EG88kJKuYs8",
          width: 1000,
          height: 667,
          url: simpleChair,
          filename: "product-4.jpeg",
          size: 49641,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: simpleChair,
              width: 54,
              height: 36,
            },
            large: {
              url: simpleChair,
              width: 768,
              height: 512,
            },
            full: {
              url: simpleChair,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attaeT2Dex98o2jfW",
          width: 1000,
          height: 667,
          url: extraProduct1,
          filename: "extra-1.jpeg",
          size: 102108,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct1,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct1,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct1,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attWsZasaaRD1P7mm",
          width: 1000,
          height: 714,
          url: extraProduct2,
          filename: "extra-2.jpeg",
          size: 84418,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct2,
              width: 50,
              height: 36,
            },
            large: {
              url: extraProduct2,
              width: 717,
              height: 512,
            },
            full: {
              url: extraProduct2,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attTvaiDcADaAItLw",
          width: 1000,
          height: 650,
          url: extraProduct3,
          filename: "extra-3.jpeg",
          size: 107838,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct3,
              width: 55,
              height: 36,
            },
            large: {
              url: extraProduct3,
              width: 788,
              height: 512,
            },
            full: {
              url: extraProduct3,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attdxQmF0aCH5I32F",
          width: 1000,
          height: 667,
          url: extraProduct4,
          filename: "extra-4.jpeg",
          size: 99481,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct4,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct4,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct4,
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      reviews: 400,
      stars: 1.2,
      name: "simple chair",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      company: "liddy",
    },
    {
      id: "recs5BSVU3qQrOj4E",
      stock: 6,
      price: 129999,
      shipping: true,
      colors: ["#00ff00", "#ffb900"],
      category: "living room",
      images: [
        {
          id: "attub6EG88kJKuYs8",
          width: 1000,
          height: 667,
          url: sofaSet,
          filename: "product-4.jpeg",
          size: 49641,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: sofaSet,
              width: 54,
              height: 36,
            },
            large: {
              url: sofaSet,
              width: 768,
              height: 512,
            },
            full: {
              url: sofaSet,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attaeT2Dex98o2jfW",
          width: 1000,
          height: 667,
          url: extraProduct1,
          filename: "extra-1.jpeg",
          size: 102108,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct1,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct1,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct1,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attWsZasaaRD1P7mm",
          width: 1000,
          height: 714,
          url: extraProduct2,
          filename: "extra-2.jpeg",
          size: 84418,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct2,
              width: 50,
              height: 36,
            },
            large: {
              url: extraProduct2,
              width: 717,
              height: 512,
            },
            full: {
              url: extraProduct2,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attTvaiDcADaAItLw",
          width: 1000,
          height: 650,
          url: extraProduct3,
          filename: "extra-3.jpeg",
          size: 107838,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct3,
              width: 55,
              height: 36,
            },
            large: {
              url: extraProduct3,
              width: 788,
              height: 512,
            },
            full: {
              url: extraProduct3,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attdxQmF0aCH5I32F",
          width: 1000,
          height: 667,
          url: extraProduct4,
          filename: "extra-4.jpeg",
          size: 99481,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct4,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct4,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct4,
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      reviews: 45,
      stars: 4.8,
      name: "sofa set",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      company: "marcos",
    },
    {
      id: "recroK1VD8qVdMP5H",
      stock: 7,
      price: 15999,
      colors: ["#ffb900"],
      category: "office",
      images: [
        {
          id: "attub6EG88kJKuYs8",
          width: 1000,
          height: 667,
          url: suedeArmchair,
          filename: "product-4.jpeg",
          size: 49641,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: suedeArmchair,
              width: 54,
              height: 36,
            },
            large: {
              url: suedeArmchair,
              width: 768,
              height: 512,
            },
            full: {
              url: suedeArmchair,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attaeT2Dex98o2jfW",
          width: 1000,
          height: 667,
          url: extraProduct1,
          filename: "extra-1.jpeg",
          size: 102108,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct1,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct1,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct1,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attWsZasaaRD1P7mm",
          width: 1000,
          height: 714,
          url: extraProduct2,
          filename: "extra-2.jpeg",
          size: 84418,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct2,
              width: 50,
              height: 36,
            },
            large: {
              url: extraProduct2,
              width: 717,
              height: 512,
            },
            full: {
              url: extraProduct2,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attTvaiDcADaAItLw",
          width: 1000,
          height: 650,
          url: extraProduct3,
          filename: "extra-3.jpeg",
          size: 107838,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct3,
              width: 55,
              height: 36,
            },
            large: {
              url: extraProduct3,
              width: 788,
              height: 512,
            },
            full: {
              url: extraProduct3,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attdxQmF0aCH5I32F",
          width: 1000,
          height: 667,
          url: extraProduct4,
          filename: "extra-4.jpeg",
          size: 99481,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct4,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct4,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct4,
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      reviews: 10,
      stars: 3.6,
      name: "suede armchair",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      company: "caressa",
    },
    {
      id: "rec7JInsuCEHgmaGe",
      stock: 11,
      price: 79999,
      featured: true,
      colors: ["#ff0000", "#00ff00"],
      category: "living room",
      images: [
        {
          id: "attub6EG88kJKuYs8",
          width: 1000,
          height: 667,
          url: utopiaSofa,
          filename: "product-4.jpeg",
          size: 49641,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: utopiaSofa,
              width: 54,
              height: 36,
            },
            large: {
              url: utopiaSofa,
              width: 768,
              height: 512,
            },
            full: {
              url: utopiaSofa,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attaeT2Dex98o2jfW",
          width: 1000,
          height: 667,
          url: extraProduct1,
          filename: "extra-1.jpeg",
          size: 102108,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct1,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct1,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct1,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attWsZasaaRD1P7mm",
          width: 1000,
          height: 714,
          url: extraProduct2,
          filename: "extra-2.jpeg",
          size: 84418,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct2,
              width: 50,
              height: 36,
            },
            large: {
              url: extraProduct2,
              width: 717,
              height: 512,
            },
            full: {
              url: extraProduct2,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attTvaiDcADaAItLw",
          width: 1000,
          height: 650,
          url: extraProduct3,
          filename: "extra-3.jpeg",
          size: 107838,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct3,
              width: 55,
              height: 36,
            },
            large: {
              url: extraProduct3,
              width: 788,
              height: 512,
            },
            full: {
              url: extraProduct3,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attdxQmF0aCH5I32F",
          width: 1000,
          height: 667,
          url: extraProduct4,
          filename: "extra-4.jpeg",
          size: 99481,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct4,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct4,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct4,
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      reviews: 10,
      stars: 2.2,
      name: "utopia sofa",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      company: "liddy",
    },
    {
      id: "rec3jeKnhInKHJuz2",
      stock: 2,
      price: 120999,
      featured: true,
      colors: ["#ff0000"],
      category: "office",
      images: [
        {
          id: "attub6EG88kJKuYs8",
          width: 1000,
          height: 667,
          url: vaseTable,
          filename: "product-4.jpeg",
          size: 49641,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: vaseTable,
              width: 54,
              height: 36,
            },
            large: {
              url: vaseTable,
              width: 768,
              height: 512,
            },
            full: {
              url: vaseTable,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attaeT2Dex98o2jfW",
          width: 1000,
          height: 667,
          url: extraProduct1,
          filename: "extra-1.jpeg",
          size: 102108,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct1,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct1,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct1,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attWsZasaaRD1P7mm",
          width: 1000,
          height: 714,
          url: extraProduct2,
          filename: "extra-2.jpeg",
          size: 84418,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct2,
              width: 50,
              height: 36,
            },
            large: {
              url: extraProduct2,
              width: 717,
              height: 512,
            },
            full: {
              url: extraProduct2,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attTvaiDcADaAItLw",
          width: 1000,
          height: 650,
          url: extraProduct3,
          filename: "extra-3.jpeg",
          size: 107838,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct3,
              width: 55,
              height: 36,
            },
            large: {
              url: extraProduct3,
              width: 788,
              height: 512,
            },
            full: {
              url: extraProduct3,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attdxQmF0aCH5I32F",
          width: 1000,
          height: 667,
          url: extraProduct4,
          filename: "extra-4.jpeg",
          size: 99481,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct4,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct4,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct4,
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      reviews: 12,
      stars: 4.9,
      name: "vase table",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      company: "marcos",
    },
    {
      id: "recv2ohxljlK2FZO7",
      stock: 49,
      price: 250099,
      colors: ["#000", "#ffb900"],
      category: "bedroom",
      images: [
        {
          id: "attub6EG88kJKuYs8",
          width: 1000,
          height: 667,
          url: woodenBed,
          filename: "product-4.jpeg",
          size: 49641,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: woodenBed,
              width: 54,
              height: 36,
            },
            large: {
              url: woodenBed,
              width: 768,
              height: 512,
            },
            full: {
              url: woodenBed,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attaeT2Dex98o2jfW",
          width: 1000,
          height: 667,
          url: extraProduct1,
          filename: "extra-1.jpeg",
          size: 102108,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct1,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct1,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct1,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attWsZasaaRD1P7mm",
          width: 1000,
          height: 714,
          url: extraProduct2,
          filename: "extra-2.jpeg",
          size: 84418,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct2,
              width: 50,
              height: 36,
            },
            large: {
              url: extraProduct2,
              width: 717,
              height: 512,
            },
            full: {
              url: extraProduct2,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attTvaiDcADaAItLw",
          width: 1000,
          height: 650,
          url: extraProduct3,
          filename: "extra-3.jpeg",
          size: 107838,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct3,
              width: 55,
              height: 36,
            },
            large: {
              url: extraProduct3,
              width: 788,
              height: 512,
            },
            full: {
              url: extraProduct3,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attdxQmF0aCH5I32F",
          width: 1000,
          height: 667,
          url: extraProduct4,
          filename: "extra-4.jpeg",
          size: 99481,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct4,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct4,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct4,
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      reviews: 300,
      stars: 4.2,
      name: "wooden bed",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      company: "ikea",
    },
    {
      id: "recJIjREF3dlFi3sR",
      stock: 5,
      price: 150999,
      shipping: true,
      colors: ["#000"],
      category: "office",
      images: [
        {
          id: "attub6EG88kJKuYs8",
          width: 1000,
          height: 667,
          url: woodenDesk,
          filename: "product-4.jpeg",
          size: 49641,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: woodenDesk,
              width: 54,
              height: 36,
            },
            large: {
              url: woodenDesk,
              width: 768,
              height: 512,
            },
            full: {
              url: woodenDesk,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attaeT2Dex98o2jfW",
          width: 1000,
          height: 667,
          url: extraProduct1,
          filename: "extra-1.jpeg",
          size: 102108,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct1,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct1,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct1,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attWsZasaaRD1P7mm",
          width: 1000,
          height: 714,
          url: extraProduct2,
          filename: "extra-2.jpeg",
          size: 84418,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct2,
              width: 50,
              height: 36,
            },
            large: {
              url: extraProduct2,
              width: 717,
              height: 512,
            },
            full: {
              url: extraProduct2,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attTvaiDcADaAItLw",
          width: 1000,
          height: 650,
          url: extraProduct3,
          filename: "extra-3.jpeg",
          size: 107838,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct3,
              width: 55,
              height: 36,
            },
            large: {
              url: extraProduct3,
              width: 788,
              height: 512,
            },
            full: {
              url: extraProduct3,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attdxQmF0aCH5I32F",
          width: 1000,
          height: 667,
          url: extraProduct4,
          filename: "extra-4.jpeg",
          size: 99481,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct4,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct4,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct4,
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      reviews: 300,
      stars: 2.2,
      name: "wooden desk",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      company: "ikea",
    },
    {
      id: "recm7wC8TBVdU9oEL",
      stock: 33,
      price: 40099,
      colors: ["#0000ff", "#00ff00"],
      category: "office",
      images: [
        {
          id: "attub6EG88kJKuYs8",
          width: 1000,
          height: 667,
          url: woodenDesk1,
          filename: "product-4.jpeg",
          size: 49641,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: woodenDesk1,
              width: 54,
              height: 36,
            },
            large: {
              url: woodenDesk1,
              width: 768,
              height: 512,
            },
            full: {
              url: woodenDesk1,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attaeT2Dex98o2jfW",
          width: 1000,
          height: 667,
          url: extraProduct1,
          filename: "extra-1.jpeg",
          size: 102108,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct1,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct1,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct1,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attWsZasaaRD1P7mm",
          width: 1000,
          height: 714,
          url: extraProduct2,
          filename: "extra-2.jpeg",
          size: 84418,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct2,
              width: 50,
              height: 36,
            },
            large: {
              url: extraProduct2,
              width: 717,
              height: 512,
            },
            full: {
              url: extraProduct2,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attTvaiDcADaAItLw",
          width: 1000,
          height: 650,
          url: extraProduct3,
          filename: "extra-3.jpeg",
          size: 107838,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct3,
              width: 55,
              height: 36,
            },
            large: {
              url: extraProduct3,
              width: 788,
              height: 512,
            },
            full: {
              url: extraProduct3,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attdxQmF0aCH5I32F",
          width: 1000,
          height: 667,
          url: extraProduct4,
          filename: "extra-4.jpeg",
          size: 99481,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct4,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct4,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct4,
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      reviews: 14,
      stars: 3.2,
      name: "wooden desk",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      company: "ikea",
    },
    {
      id: "rectfNsySwAJeWDN2",
      stock: 5,
      price: 234999,
      shipping: true,
      featured: true,
      colors: ["#ffb900", "#ff0000"],
      category: "kitchen",
      images: [
        {
          id: "attub6EG88kJKuYs8",
          width: 1000,
          height: 667,
          url: woodenTable,
          filename: "product-4.jpeg",
          size: 49641,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: woodenTable,
              width: 54,
              height: 36,
            },
            large: {
              url: woodenTable,
              width: 768,
              height: 512,
            },
            full: {
              url: woodenTable,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attaeT2Dex98o2jfW",
          width: 1000,
          height: 667,
          url: extraProduct1,
          filename: "extra-1.jpeg",
          size: 102108,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct1,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct1,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct1,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attWsZasaaRD1P7mm",
          width: 1000,
          height: 714,
          url: extraProduct2,
          filename: "extra-2.jpeg",
          size: 84418,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct2,
              width: 50,
              height: 36,
            },
            large: {
              url: extraProduct2,
              width: 717,
              height: 512,
            },
            full: {
              url: extraProduct2,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attTvaiDcADaAItLw",
          width: 1000,
          height: 650,
          url: extraProduct3,
          filename: "extra-3.jpeg",
          size: 107838,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct3,
              width: 55,
              height: 36,
            },
            large: {
              url: extraProduct3,
              width: 788,
              height: 512,
            },
            full: {
              url: extraProduct3,
              width: 3000,
              height: 3000,
            },
          },
        },
        {
          id: "attdxQmF0aCH5I32F",
          width: 1000,
          height: 667,
          url: extraProduct4,
          filename: "extra-4.jpeg",
          size: 99481,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: extraProduct4,
              width: 54,
              height: 36,
            },
            large: {
              url: extraProduct4,
              width: 768,
              height: 512,
            },
            full: {
              url: extraProduct4,
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      reviews: 35,
      stars: 3.4,
      name: "wooden table",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
      company: "caressa",
    },
  ];